---
title: "ST558 Project 2 (Tuesday)"
author: "Mu-Tien, Lee"
output: 
  github_document:
      toc: true

---
```{r setup2, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, error = FALSE, message=FALSE)
```

```{r package}
library(tibble)
library(knitr)
library(rmarkdown)

```

```{r render the file}
render("ST558_project2_Monday.Rmd",
       output_format = "github_document",
       output_file = "Tuesday.md",
       params =list(w=2))

render("ST558_project2_Monday.Rmd",
       output_format = "github_document",
       output_file = "Wednesday.md",
       params =list(w=3))

render("ST558_project2_Monday.Rmd",
       output_format = "github_document",
       output_file = "Thursday.md",
       params =list(w=4))

render("ST558_project2_Monday.Rmd",
       output_format = "github_document",
       output_file = "Friday.md",
       params =list(w=5))

render("ST558_project2_Monday.Rmd",
       output_format = "github_document",
       output_file = "Saturday.md",
       params =list(w=6))
render("ST558_project2_Monday.Rmd",
       output_format = "github_document",
       output_file = "Sunday.md",
       params =list(w=0))
```

