---
title: "ST558 Project 2"
author: "Mu-Tien, Lee"
output: 
  github_document:
      toc: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, error = FALSE, message=FALSE)
```

# Introduction
The main purpose of the project is to build a model that can predict the count of rantal of bikes.\
During the project, I'm going to use the bike sharing data from [UCI machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Bike+Sharing+Dataset). This file contain the data of the bicycle rentaling. There are two different dataset. One of them contain the date, season,year, month, holiday or not, weekday, workingday or not, weather situation, temperature, feeling temperature, humidity, windspeed, and the count. It also contain the record to see if the person is a casual user or registered, however, I don't take this into my consideration. The other one contain all same variables but more detail about the time with hour variable that shows what time did the bicycle was rented. Since I personal think the count of the rental will have huge difference between times. I would like to use the dataset with hour variables to do this project.\

I am going to use two different method to build my model.First, I will use leave one out cross validation to fit a tree-based regression model. Secondly, I will fit a boosted tree model using cross validation. After that, I will provide some prediction. Most importantly, I will compare these two model, and see which one is better on predicting the rental count of bicycle. Notice that I'm going to separate my data by weekday. That is to say each weekday will have their own best model.\


# Analysis

click below links to check the analysis of each weekday.\
[Monday analysis](ST558_project2_Monday.md)\

[Tuesday analysis](2 .md) \

[Wednesday analysis](3 .md) \

[Thursday analysis](4 .md) \

[Friday analysis](5 .md) \

[Saturday analysis](6 .md) \

[Sunday analysis](0 .md) \


In these analysis, we can see that the boosted tree model has the smaller RMSE on all the training model compare to the tree-base model.
